# Generated by Django 4.0.2 on 2022-02-28 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heading', models.CharField(max_length=70)),
                ('content', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ('date',),
            },
        ),
    ]
