# Generated by Django 4.0.3 on 2022-03-06 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('header', models.CharField(max_length=70)),
                ('content', models.TextField()),
            ],
            options={
                'ordering': ('date',),
            },
        ),
    ]
