# Generated by Django 4.0.2 on 2022-03-21 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0002_alter_entry_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ('date', 'header')},
        ),
    ]
